version: '3.7'
services:
  # demorest-app
  demorest-app:
    image: maven:3.5.0-jdk-8
    container_name: demorest-app
    command: "/opt/rest-demo/bin/run.sh"
    volumes:
      - ~/.m2:/root/.m2
      - ../.:/opt/rest-demo
    ports:
      - "8080:8080"

